backend:
  name: github
  repo: suhagthakor3262-lang/username.github.13 # Aapki repository ka naam
  branch: main
  base_url: https://identity.netlify.com # Yeh free identity tool background mein kaam karega

media_folder: "images"
public_folder: "images"

collections:
  - name: "games"
    label: "All Games"
    folder: "data/games"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Game Name", name: "title", widget: "string" }
      - { label: "App Download Link", name: "app_link", widget: "string" }
      - { label: "Image Link (URL)", name: "image_link", widget: "string" }
      - { label: "Bonus Text", name: "bonus", widget: "string", default: "Bonus 100" }
      - { label: "Withdrawal Text", name: "withdrawal", widget: "string", default: "Withdrawal 100" }
      
